### ISSUE TITLE
Missing MotionPlanningGoal or MotionPlanningEnv

### ISSUE THREAD

**Issue by maxspahn** [maxspahn/gym_envs_urdf#136]
Installing the bare minimum of the package leads to missing some package.
This might throw an error like:

```
warnings.warn(str(err))
Traceback (most recent call last):
  File "/home/josyula/Programs/MAS_Project/gym_envs_urdf/examples/multi_robot.py", line 51, in <module>
    run_multi_robot(render=True, obstacles=True, goal=True)
  File "/home/josyula/Programs/MAS_Project/gym_envs_urdf/examples/multi_robot.py", line 34, in run_multi_robot
    from examples.scene_objects.goal import dynamicGoal
  File "/home/josyula/Programs/MAS_Project/gym_envs_urdf/examples/scene_objects/goal.py", line 1, in <module>
    from MotionPlanningGoal.staticSubGoal import StaticSubGoal
ModuleNotFoundError: No module named 'MotionPlanningGoal'
```

**Comment by Capsar** [comment]
Tried the top command, but there is a small typo: should be `pip install "urdfenvs[scenes]"`

**Comment by maxspahn** [comment]
In #148, the dependency changed from optional to required, thus making the installation easier in the future.
