### ISSUE TITLE
Errors in numpy models when creating a new env via Conda.

### ISSUE THREAD

**Issue by DasWilheim** [maxspahn/gym_envs_urdf#145]
Dear fellow students and TA's

I am making a read.me on how to initialize a new env via Conda. My goal is that anyone can run the codes and the whole env will run. So far I managed to run the code in my base env, but when I initialize a new one errors occur. This is what I have done so far:

Run the following code in your terminal:

conda create --name testenv python==3.8.8   (Conda 3.10 gives errors)
conda activate testenv

pip install motion-planning-scenes
pip install cvxpy
pip install shapely

conda install -c anaconda git
git clone https://github.com/maxspahn/gym_envs_urdf.git

cd gym_envs_urdf
pip3 install .

When I try to run "python3 point_robot.py" at this point I get an error 
AttributeError: module 'numpy' has no attribute 'int'

This error occurs due to the fact that NumPy is downloaded using "pip install". I managed to tackle this error by executing this:
pip uninstall numpy
conda install numpy           ( it will install numpy 1.23.5)

NOW my code runs the example "python3 point_robot.py"

But when I try to run my own code, there occurs an error eventually. at first it initializes good, you can see the robots:
![image](https://user-images.githubusercontent.com/117392093/211193963-283ec6ed-4af2-4295-a0bc-a1be79617a15.png)

But when it tries to load the walls the following error occurs:

AttributeError: 'Symbol' object has no attribute 'sin'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 270, in <module>
    behaviour()
  File "main.py", line 60, in behaviour
    env , m , currentPositions, currentVelocities, currentOrientations, obstacles,  steeringInput = initEnv(goal=True, maps=1)
  File "C:\Users\wille\OneDrive\Documenten\Tu Delft\Msc, Robotics\2nd Year\Q2\Planning and Decision making\Planning_and_decision_making\env\holonomic_robot_main_test.py", line 90, in initEnv
    from env.gym_envs_urdf.scene_objects.obstacles import walls1
  File "C:\Users\wille\OneDrive\Documenten\Tu Delft\Msc, Robotics\2nd Year\Q2\Planning and Decision making\Planning_and_decision_making\env\gym_envs_urdf\scene_objects\obstacles.py", line 95, in <module>
    dynamicSphereObst2 = DynamicSphereObstacle(name="simpleSphere", content_dict=dynamicObst2Dict)
  File "C:\Users\wille\anaconda3\envs\testenv7\lib\site-packages\MotionPlanningEnv\dynamicSphereObstacle.py", line 84, in __init__
    self._traj = AnalyticTrajectory(
  File "C:\Users\wille\anaconda3\envs\testenv7\lib\site-packages\MotionPlanningSceneHelpers\analyticTrajectory.py", line 26, in __init__
    self._traj = [eval(x) for x in kwargs.get('traj')]
  File "C:\Users\wille\anaconda3\envs\testenv7\lib\site-packages\MotionPlanningSceneHelpers\analyticTrajectory.py", line 26, in <listcomp>
    self._traj = [eval(x) for x in kwargs.get('traj')]
  File "<string>", line 1, in <module>
TypeError: loop of ufunc does not support argument 0 of type Symbol which has no callable sin method

In this site-package an error occurs, MotionPlanningSceneHelpers\analyticTrajectory.py

I tried to use different versions of NumPy but that did not help..

if someone has a solution to this error I would be very happy!

**Comment by maxspahn** [comment]
Hi @DasWilheim ,

Great to see that you put so much effort in this. Generally, you could also install the package from the pypi index using `pip install urdfenvs`. That also works in a conda environment and it should be more stable then the master branch here.

>This error occurs due to the fact that NumPy is downloaded using "pip install". I managed to tackle this error by executing this:
pip uninstall numpy
conda install numpy ( it will install numpy 1.23.5)

I stumbled across this problem as well, because too recent versions of numpy removed the variables `np.int` (`np.float32`) and so on. I will fix this today.

> But when it tries to load the walls the following error occurs:
AttributeError: 'Symbol' object has no attribute 'sin'

This is related to your definitions of obstacles and goals. Could you post these definitions here|?

Thanks for the effort and your reporting on these issues.
